build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        TARGET: x64
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        TARGET: x64
      - PRJ_GEN: "Visual Studio 12 2013"
        BDIR: msvc2013
        TARGET: x86
      - PRJ_GEN: "Visual Studio 14 2015"
        BDIR: msvc2015
        TARGET: x86

build_script:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - cmake .. -G"%PRJ_GEN%"
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%
    - cmake --build . --config Release --target install
    - ctest -V --output-on-failure -C Release

test_script:
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\athr.lib exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\bin\athr.dll exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\athr_static.lib exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\include\athr.h exit 1
